apiVersion: v1
kind: Service
metadata:
  name: {{ include "pruebaweb.fullname" . }}
  labels:
    {{- include "pruebaweb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pruebaweb.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{- end }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.metricsNodePort }}
      {{- end }}